baseURL = "https://state-demo.zxdx.dev/"
languageCode = "en-us"
title = "Site is Off"
theme = "pulp"

[params]
    author = "Site is Turned Off"
    avatar = "red.gif"
    description = """
        Load balancer is pointing to the "Off" bucket
    """
    publicationYear = "2019"